# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '44 18 * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  container_job:
    runs-on: ubuntu-latest
    container:
      image: minio/mc
    steps:
      - name: alies minio bucket
        env:
          DEST_MINIO_HOST: ${{ secrets.DEST_MINIO_HOST }}
          DEST_MINIO_ACCESS_KEY: ${{ secrets.DEST_MINIO_ACCESS_KEY }}
          DEST_MINIO_SECRET_KEY: ${{ secrets.DEST_MINIO_SECRET_KEY }}
          DEST_MINIO_BUCKET: ${{ secrets.DEST_MINIO_BUCKET }}
          SOURCE_MINIO_HOST: ${{ secrets.SOURCE_MINIO_HOST }}
          SOURCE_MINIO_ACCESS_KEY: ${{ secrets.SOURCE_MINIO_ACCESS_KEY }}
          SOURCE_MINIO_SECRET_KEY: ${{ secrets.SOURCE_MINIO_SECRET_KEY }}
          SOURCE_MINIO_BUCKET: ${{ secrets.SOURCE_MINIO_BUCKET }}
        run: (mc alias set destBucket $DEST_MINIO_HOST $DEST_MINIO_ACCESS_KEY $DEST_MINIO_SECRET_KEY && mc alias set sourceBucket $SOURCE_MINIO_HOST $SOURCE_MINIO_ACCESS_KEY $SOURCE_MINIO_SECRET_KEY)
      - name: buckupAll
        run: mc cp sourceBucket/$SOURCE_MINIO_BUCKET  destBucket/$DEST_MINIO_BUCKET 2>&1 >/dev/null
